java_binary(
    name = "eval_client",
    srcs = ["EvalClient.java"],
    main_class = "EvalClient",
)

java_binary(
    name = "eval_server",
    srcs = ["EvalServer.java"],
    main_class = "EvalServer",
)

java_binary(
    name = "threaded_eval_server",
    srcs = [
        "ThreadedEvalServer.java",
        "ClientHandler.java",
    ],
    main_class = "ThreadedEvalServer",
)


